FROM ubuntu:16.10

# Usar repositorios old-releases
RUN sed -i 's|archive.ubuntu.com|old-releases.ubuntu.com|g' /etc/apt/sources.list && \
    sed -i 's|security.ubuntu.com|old-releases.ubuntu.com|g' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y openssh-client iputils-ping && \
    apt-get clean

CMD ["/bin/bash"]
